# Generated by Django 3.0.8 on 2020-09-09 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appliance_name', models.CharField(max_length=30)),
                ('appliance_image', models.ImageField(upload_to='main_images_videos/')),
                ('appliance_description', models.CharField(max_length=200)),
                ('purchase_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='RecipeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, unique=True)),
                ('category_image', models.ImageField(default=None, upload_to='main_images_videos/')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=30)),
                ('recipe_description', models.CharField(max_length=200)),
                ('ingredient_list', models.TextField()),
                ('recipe_procedure', models.TextField()),
                ('no_servings', models.PositiveIntegerField()),
                ('prep_time', models.CharField(max_length=30)),
                ('cook_time', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='main_images_videos/')),
                ('video', models.FileField(upload_to='main_images_videos/')),
                ('veg_nonveg', models.BinaryField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.RecipeCategory', verbose_name='RecipeCategory')),
            ],
        ),
    ]
