# Generated by Django 3.0.8 on 2020-09-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200910_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalrecipe',
            name='recipe_slug',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='recipecategory',
            name='category_slug',
            field=models.CharField(default=1, max_length=200),
        ),
    ]
