# Generated by Django 3.0.3 on 2020-09-21 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200911_0005'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplianceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, unique=True)),
                ('category_image', models.ImageField(default=None, upload_to='main_images/')),
                ('category_slug', models.CharField(default=1, max_length=200, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='appliance',
            name='appliance_slug',
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='purchase_link',
            field=models.URLField(max_length=500),
        ),
        migrations.AddField(
            model_name='appliance',
            name='appliance_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.ApplianceCategory', verbose_name='ApplianceCategory'),
        ),
    ]
