# Generated by Django 3.0.8 on 2020-09-11 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200911_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalrecipe',
            name='video',
            field=models.TextField(default=1),
        ),
    ]
