# Generated by Django 3.0.3 on 2020-09-21 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200921_0807'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appliancecategory',
            options={'verbose_name_plural': 'Appliance Catogories'},
        ),
        migrations.AlterModelOptions(
            name='recipecategory',
            options={'verbose_name_plural': 'Recipe Catogories'},
        ),
        migrations.RemoveField(
            model_name='appliance',
            name='appliance_slug',
        ),
        migrations.AlterField(
            model_name='appliance',
            name='appliance_image',
            field=models.ImageField(upload_to='main_images/appliances'),
        ),
        migrations.AlterField(
            model_name='appliancecategory',
            name='category_image',
            field=models.ImageField(default=None, upload_to='main_images/appliances'),
        ),
    ]
