# Generated by Django 3.0.8 on 2020-09-24 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200924_1938'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appliance',
        ),
        migrations.DeleteModel(
            name='ApplianceCategory',
        ),
    ]
