# Generated by Django 3.0.8 on 2020-09-24 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200924_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplianceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, unique=True)),
                ('category_image', models.ImageField(default=None, upload_to='main_images/appliances')),
                ('category_slug', models.CharField(default=1, max_length=200, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Appliance Catogories',
            },
        ),
    ]
