# Generated by Django 3.0.8 on 2020-09-24 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_delete_appliancecategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplianceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, unique=True)),
                ('category_image', models.ImageField(default=None, upload_to='main_images/appliances')),
                ('category_slug', models.CharField(default=1, max_length=200, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Appliance Catogories',
            },
        ),
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appliance_name', models.CharField(max_length=30)),
                ('appliance_description', models.CharField(max_length=200)),
                ('appliance_image', models.ImageField(upload_to='main_images/appliances')),
                ('purchase_link', models.URLField(max_length=500)),
                ('appliance_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.ApplianceCategory', verbose_name='ApplianceCategory')),
            ],
        ),
    ]
