# Generated by Django 3.0.8 on 2020-09-09 18:05

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enduser_name', models.CharField(max_length=30)),
                ('enduser_email', models.EmailField(max_length=254, unique=True)),
                ('enduser_dob', models.DateField(default=datetime.date.today)),
                ('enduser_password', models.CharField(max_length=15)),
                ('enduser_photo', models.ImageField(upload_to='enduser_images_videos/')),
                ('enduser_bio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EndUserRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=30)),
                ('recipe_description', models.CharField(max_length=200)),
                ('ingredient_list', models.TextField()),
                ('recipe_procedure', models.TextField()),
                ('no_servings', models.PositiveIntegerField()),
                ('prep_time', models.CharField(max_length=30)),
                ('cook_time', models.CharField(max_length=30)),
                ('video', models.FileField(upload_to='')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('post_type', models.BinaryField()),
                ('enduser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enduser.EndUser')),
            ],
        ),
        migrations.CreateModel(
            name='EndUserRecipeLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likeduser_type', models.CharField(max_length=20)),
                ('likeduser_objectid', models.PositiveIntegerField()),
                ('likeduser_modeltype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType')),
                ('recipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enduser.EndUserRecipe')),
            ],
        ),
        migrations.CreateModel(
            name='EndUserRecipeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='enduser_images_videos/')),
                ('recipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enduser.EndUserRecipe')),
            ],
        ),
        migrations.CreateModel(
            name='EndUserRecipeFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posteduser_type', models.CharField(max_length=20)),
                ('posteduser_objectid', models.PositiveIntegerField()),
                ('feedback', models.TextField()),
                ('posteduser_modeltype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType')),
                ('recipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enduser.EndUserRecipe')),
            ],
        ),
        migrations.CreateModel(
            name='EndUserFollowers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower_type', models.CharField(max_length=20)),
                ('follower_objectid', models.PositiveIntegerField()),
                ('enduser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enduser.EndUser')),
                ('follower_modeltype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType')),
            ],
        ),
    ]
