# Generated by Django 3.0.8 on 2020-09-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enduser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enduserrecipe',
            name='video',
        ),
        migrations.AlterField(
            model_name='enduser',
            name='enduser_photo',
            field=models.ImageField(upload_to='enduser_images/'),
        ),
        migrations.AlterField(
            model_name='enduserrecipe',
            name='post_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='enduserrecipeimage',
            name='image',
            field=models.ImageField(upload_to='enduser_images/'),
        ),
    ]
