# Generated by Django 3.0.8 on 2020-09-10 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enduser', '0003_auto_20200910_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='enduser',
            name='enduser_city',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='enduser',
            name='enduser_country',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='enduser',
            name='enduser_state',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
