# Generated by Django 3.0.8 on 2020-09-14 09:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('enduser', '0004_auto_20200910_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='enduser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
