# Generated by Django 3.0.8 on 2020-09-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enduser', '0007_auto_20200916_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='enduser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
