# Generated by Django 3.0.8 on 2020-09-09 18:05

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chef_name', models.CharField(max_length=30)),
                ('chef_email', models.EmailField(max_length=254, unique=True)),
                ('chef_password', models.CharField(max_length=15)),
                ('chef_dob', models.DateField(default=datetime.date.today)),
                ('chef_photo', models.ImageField(upload_to='main_images_videos_files/')),
                ('chef_bio', models.TextField(default='None')),
                ('validation_counts', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ChefDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.FileField(unique=True, upload_to='main_images_videos_files/')),
            ],
        ),
        migrations.CreateModel(
            name='ChefExpertiseArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ChefFollowers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower_type', models.CharField(max_length=20)),
                ('follower_objectid', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ChefRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=30)),
                ('recipe_description', models.CharField(max_length=200)),
                ('ingredient_list', models.TextField()),
                ('recipe_procedure', models.TextField()),
                ('no_servings', models.PositiveIntegerField(default=0)),
                ('prep_time', models.CharField(max_length=30)),
                ('cook_time', models.CharField(max_length=30)),
                ('video', models.FileField(upload_to='')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('post_type', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='ChefRecipeFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posteduser_type', models.CharField(max_length=20)),
                ('posteduser_objectid', models.PositiveIntegerField()),
                ('feedback', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ChefRecipeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='chef_images_videos_files/')),
            ],
        ),
        migrations.CreateModel(
            name='ChefRecipeLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likeduser_type', models.CharField(max_length=20)),
                ('likeduser_objectid', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=50)),
                ('event_description', models.TextField()),
                ('event_datetime', models.DateTimeField()),
                ('event_duration', models.CharField(default=0, max_length=30)),
                ('event_type', models.CharField(max_length=20)),
                ('event_amount', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reguser_type', models.CharField(max_length=20)),
                ('reguser_objectid', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserRecipesValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BinaryField()),
                ('chef', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chef.Chef')),
            ],
        ),
    ]
