# Generated by Django 3.0.8 on 2020-09-09 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enduser', '0001_initial'),
        ('chef', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecipesvalidation',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enduser.EndUser'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chef.Event'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='reguser_modeltype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='event',
            name='chef_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chef.Chef', verbose_name='Chef id'),
        ),
        migrations.AddField(
            model_name='chefrecipelike',
            name='likeduser_modeltype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='chefrecipelike',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chef.ChefRecipe'),
        ),
        migrations.AddField(
            model_name='chefrecipeimage',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chef.ChefRecipe'),
        ),
        migrations.AddField(
            model_name='chefrecipefeedback',
            name='posteduser_modeltype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='chefrecipefeedback',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chef.ChefRecipe'),
        ),
        migrations.AddField(
            model_name='chefrecipe',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.RecipeCategory'),
        ),
        migrations.AddField(
            model_name='chefrecipe',
            name='chef',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chef.Chef'),
        ),
        migrations.AddField(
            model_name='cheffollowers',
            name='chef',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chef.Chef'),
        ),
        migrations.AddField(
            model_name='cheffollowers',
            name='follower_modeltype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='chefexpertisearea',
            name='chef',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chef.Chef'),
        ),
        migrations.AddField(
            model_name='chefexpertisearea',
            name='expertise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.RecipeCategory'),
        ),
        migrations.AddField(
            model_name='chefdoc',
            name='chef',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chef.Chef', verbose_name='Chef id'),
        ),
    ]
