# Generated by Django 3.0.8 on 2020-09-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0002_auto_20200909_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chefrecipe',
            name='video',
        ),
        migrations.AlterField(
            model_name='chef',
            name='chef_photo',
            field=models.ImageField(upload_to='chef_images_files/'),
        ),
        migrations.AlterField(
            model_name='chefdoc',
            name='doc',
            field=models.FileField(unique=True, upload_to='chef_images_files/'),
        ),
        migrations.AlterField(
            model_name='chefrecipe',
            name='post_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='chefrecipeimage',
            name='image',
            field=models.ImageField(upload_to='chef_images_files/'),
        ),
        migrations.AlterField(
            model_name='userrecipesvalidation',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
