# Generated by Django 3.0.8 on 2020-09-10 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('chef', '0003_auto_20200910_0010'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChefFollowers',
            new_name='ChefFollower',
        ),
    ]
