# Generated by Django 3.0.8 on 2020-09-10 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0004_auto_20200910_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='chef_city',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='chef',
            name='chef_country',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='chef',
            name='chef_state',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
