# Generated by Django 3.0.8 on 2020-09-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0006_chef_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chef',
            name='chef_city',
        ),
        migrations.RemoveField(
            model_name='chef',
            name='chef_country',
        ),
        migrations.RemoveField(
            model_name='chef',
            name='chef_state',
        ),
        migrations.AlterField(
            model_name='chef',
            name='chef_bio',
            field=models.TextField(default='-'),
        ),
    ]
